'use strict';

const preset = exports;

preset.rules = {
  'for-direction': 'error',
  'getter-return': 'error',
  'no-await-in-loop': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': ['error', 'always'],
  'no-console': 'error',
  'no-constant-condition': ['error', { checkLoops: false }],
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-dupe-args': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-empty': ['error', { allowEmptyCatch: true }],
  'no-empty-character-class': 'error',
  'no-extra-boolean-cast': 'error',
  'no-extra-parens': ['error', 'all', {
    enforceForArrowConditionals: false,
    nestedBinaryExpressions: false,
    ignoreJSX: 'multi-line',
    returnAssign: false,
  }],
  'no-extra-semi': 'error',
  'no-func-assign': 'error',
  'no-inner-declarations': 'error',
  'no-invalid-regexp': ['error', { allowConstructorFlags: ['u', 'y'] }],
  'no-irregular-whitespace': 'error',
  'no-obj-calls': 'error',
  'no-regex-spaces': 'error',
  'no-sparse-arrays': 'error',
  'no-template-curly-in-string': 'error',
  'no-unexpected-multiline': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'use-isnan': 'error',
  'valid-jsdoc': ['error', {
    requireReturnDescription: false,
    requireParamDescription: false,
    prefer: {
      return: 'returns',
      param: 'param',
      class: 'class',
    },
    preferType: {
      Boolean: 'Boolean',
      Number: 'Number',
      String: 'String',
    },
  }],
  'valid-typeof': 'error',
};
